create_table_sql ='''
	create table 
	if not exists arbitrage5 (
	BTC1  integer DEFAULT(NULL),
	BTC2  integer DEFAULT(NULL),
	ETH1  integer DEFAULT(NULL), 
	ETH2  integer DEFAULT(NULL),
	XRP1  integer DEFAULT(NULL), 
	XRP2  integer DEFAULT(NULL), 
	LTC1  integer DEFAULT(NULL),
	LTC2  integer DEFAULT(NULL),
	BCH1  integer DEFAULT(NULL),
	BCH2  integer DEFAULT(NULL),
	OMG1  integer DEFAULT(NULL),
	OMG2  integer DEFAULT(NULL),
	ZRX1  integer DEFAULT(NULL),
	ZRX2  integer DEFAULT(NULL),
	GNT1  integer DEFAULT(NULL),
	GNT2  integer DEFAULT(NULL),
	TRX1  integer DEFAULT(NULL),
	TRX2  integer DEFAULT(NULL),
	XLM1  integer DEFAULT(NULL),
	XLM2  integer DEFAULT(NULL),
	NEO1  integer DEFAULT(NULL),
	NEO2  integer DEFAULT(NULL),
	EOS1  integer DEFAULT(NULL),
	EOS2  integer DEFAULT(NULL),
	ONT1  integer DEFAULT(NULL),
	ONT2  integer DEFAULT(NULL),

	BTC  integer DEFAULT(NULL), 
	ETH  integer DEFAULT(NULL),
	XRP  integer DEFAULT(NULL),
	LTC  integer DEFAULT(NULL),
	BCH  integer DEFAULT(NULL),
	OMG  integer DEFAULT(NULL),
	ZRX  integer DEFAULT(NULL),
	GNT  integer DEFAULT(NULL),
	TRX  integer DEFAULT(NULL),
	XLM  integer DEFAULT(NULL),
	NEO  integer DEFAULT(NULL),
	EOS  integer DEFAULT(NULL),
	ONT  integer DEFAULT(NULL),

	time date,
	type char
	);
	'''