create_table_sql ='''
	create table 
	if not exists arbitrage4 (
	BTC1  integer DEFAULT(NULL),
	BTC2  integer DEFAULT(NULL),
	ETH1  integer DEFAULT(NULL), 
	ETH2  integer DEFAULT(NULL),
	XRP1  integer DEFAULT(NULL), 
	XRP2  integer DEFAULT(NULL), 
	LTC1  integer DEFAULT(NULL),
	LTC2  integer DEFAULT(NULL),
	BCH1  integer DEFAULT(NULL),
	BCH2  integer DEFAULT(NULL),
	OMG1  integer DEFAULT(NULL),
	OMG2  integer DEFAULT(NULL),
	REQ1  integer DEFAULT(NULL),
	REQ2  integer DEFAULT(NULL),
	ZRX1  integer DEFAULT(NULL),
	ZRX2  integer DEFAULT(NULL),
	GNT1  integer DEFAULT(NULL),
	GNT2  integer DEFAULT(NULL),
	BAT1  integer DEFAULT(NULL),
	BAT2  integer DEFAULT(NULL),
	AE1   integer DEFAULT(NULL),
	AE2   integer DEFAULT(NULL),
	TRX1  integer DEFAULT(NULL),
	TRX2  integer DEFAULT(NULL),
	XLM1  integer DEFAULT(NULL),
	XLM2  integer DEFAULT(NULL),
	NEO1  integer DEFAULT(NULL),
	NEO2  integer DEFAULT(NULL),
	GAS1  integer DEFAULT(NULL),
	GAS2  integer DEFAULT(NULL),
	XRB1  integer DEFAULT(NULL),
	XRB2  integer DEFAULT(NULL),
	NCASH1  integer DEFAULT(NULL),
	NCASH2  integer DEFAULT(NULL),
	AION1  integer DEFAULT(NULL)
	AION2  integer DEFAULT(NULL),
	EOS1  integer DEFAULT(NULL),
	EOS2  integer DEFAULT(NULL),
	ONT1  integer DEFAULT(NULL),
	ONT2  integer DEFAULT(NULL),
	ZIL1  integer DEFAULT(NULL),
	ZIL2  integer DEFAULT(NULL),
	ZCO1  integer DEFAULT(NULL),
	ZCO2  integer DEFAULT(NULL),
	IOST1  integer DEFAULT(NULL), 
	IOST2  integer DEFAULT(NULL),

	BTC  integer DEFAULT(NULL), 
	ETH  integer DEFAULT(NULL),
	XRP  integer DEFAULT(NULL),
	LTC  integer DEFAULT(NULL),
	BCH  integer DEFAULT(NULL),
	OMG  integer DEFAULT(NULL),
	REQ  integer DEFAULT(NULL),
	ZRX  integer DEFAULT(NULL),
	GNT  integer DEFAULT(NULL),
	BAT  integer DEFAULT(NULL),
	AE   integer DEFAULT(NULL),
	TRX  integer DEFAULT(NULL),
	XLM  integer DEFAULT(NULL),
	NEO  integer DEFAULT(NULL),
	GAS  integer DEFAULT(NULL),
	XRB  integer DEFAULT(NULL),
	NCASH  integer DEFAULT(NULL),
	AION  integer DEFAULT(NULL),
	EOS  integer DEFAULT(NULL),
	ONT  integer DEFAULT(NULL),
	ZIL  integer DEFAULT(NULL),
	ZCO  integer DEFAULT(NULL),
	IOST  integer DEFAULT(NULL),

	time date,
	type char
	);
	'''